#24 test with venv

diff --git a/.github/workflows/test_package.yaml b/.github/workflows/test_package.yaml
--- a/.github/workflows/test_package.yaml
+++ b/.github/workflows/test_package.yaml
@@ -36,16 +36,13 @@ jobs:
           pip install .[test]
           echo $GITHUB_PATH
           echo "venv/bin" >> $GITHUB_PATH
-          echo $GITHUB_PATH
-          echo $GITHUB_ENV
           echo PATH=$PATH >> $GITHUB_ENV
-          echo $GITHUB_ENV
 
-      - name: Code Validation Stage
-        run: |
-          which python
-          exit 1
-          pre-commit run --all-files --show-diff-on-failure
+      #- name: Code Validation Stage
+      #  run: |
+      #    which python
+      #    exit 1
+      #    pre-commit run --all-files --show-diff-on-failure
       - name: Test stage
         run: |
           pip list
